import json
import re
import ast
from src.i18n import _
from typing import Any, Type, TypeVar
from pydantic import BaseModel

T = TypeVar("T", bound=BaseModel)

_LIST_PARSERS = (json.loads, lambda s: json.loads(repair_truncated_json(s)), ast.literal_eval)


def _try_parse_list(parser, val_str: str) -> list | None:
    try:
        res = parser(val_str)
    except Exception:
        return None
    return res if isinstance(res, list) else None


def safe_parse_json_list(val: Any) -> list:
    """Safely convert any string/JSON generated by LLM to Python list."""
    if isinstance(val, list):
        return val
    if not isinstance(val, str):
        return []
    val_str = val.strip()
    if not val_str:
        return []
    for parser in _LIST_PARSERS:
        parsed = _try_parse_list(parser, val_str)
        if parsed is not None:
            return parsed
    return []


def _find_json_start(json_str: str) -> int:
    for i, char in enumerate(json_str):
        if char in ("{", "["):
            return i
    return -1


def _try_pop(stack: list, open_char: str, close_char: str, char: str) -> bool:
    """Try to close a bracket/brace. Returns True if successful."""
    if char == close_char and stack and stack[-1] == open_char:
        stack.pop()
        return True
    return False


def _scan_json_structure(json_str: str) -> tuple[list, bool]:
    """Track opening stack and string/escape state of JSON."""
    stack = []
    in_string = False
    escape = False
    for char in json_str:
        if escape:
            escape = False
            continue
        if char == "\\":
            escape = True
            continue
        if char == '"':
            in_string = not in_string
            continue
        if not in_string:
            if char in ("{", "["):
                stack.append(char)
            _try_pop(stack, "{", "}", char)
            _try_pop(stack, "[", "]", char)
    return stack, in_string


def repair_truncated_json(json_str: str) -> str:
    json_str = json_str.strip()
    if not json_str:
        return "{}"

    start_idx = _find_json_start(json_str)
    if start_idx == -1:
        return json_str
    json_str = json_str[start_idx:]

    stack, in_string = _scan_json_structure(json_str)

    # If truncated inside a string, close the quote
    if in_string:
        json_str += '"'

    # Remove trailing commas or colons before closing structures
    json_str = json_str.rstrip(",: \t\n\r")

    # Se foi cortado dentro de uma string, fecha a aspa
    closing_map = {"{": "}", "[": "]"}
    json_str += "".join(closing_map.get(open_char, "") for open_char in reversed(stack))
    return json_str


def _default_or_error(target_model: Type[T], message: str) -> T:
    try:
        return target_model()
    except Exception:
        raise ValueError(message)


def _extract_code_fence(cleaned: str) -> str | None:
    """Extract content from ```json ... ``` code fence using linear search (no regex)."""
    start = cleaned.find("```")
    if start == -1:
        return None
    content_start = cleaned.find("\n", start)
    if content_start == -1:
        return ""
    content_start += 1
    end = cleaned.find("```", content_start)
    content = cleaned[content_start:end] if end != -1 else cleaned[content_start:]
    return content.strip()


def _extract_json_block(cleaned: str) -> str:
    fence_content = _extract_code_fence(cleaned)
    if fence_content is not None:
        return fence_content
    brace_match = re.search(r"(\{[\s\S]*|\[[\s\S]*)", cleaned)
    return brace_match.group(1).strip() if brace_match else cleaned


def extract_and_parse_json(text: str, target_model: Type[T]) -> T:
    """
    Extracts, repairs, and validates JSON from LLM responses, handling:
    - Empty responses (instantiates the Pydantic model defaults)
    - Markdown code blocks (```json ... ```)
    - Thinking tags (<think>...</think>)
    - Truncation due to token limits
    - Direct arrays [...] when an object {field: [...]} is expected
    """
    if not text or not text.strip():
        return _default_or_error(
            target_model,
            _("The LLM returned a completely empty response for {model}.").format(model=target_model.__name__)
        )

    cleaned = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    if not cleaned:
        return _default_or_error(target_model, _("The LLM returned only empty thinking tags."))

    cleaned = _extract_json_block(cleaned)
    if not cleaned:
        return _default_or_error(target_model, _("No JSON block was found in the LLM response."))

    parsed_data = _loads_with_repair(cleaned, text)

    # If the LLM returned a direct list [...] when the model expected an object {field: [...]}:
    if isinstance(parsed_data, list):
        # Find the first field that accepts a list/sequence
        list_field = next(
            (name for name, field in target_model.model_fields.items() 
            if getattr(field.annotation, "__origin__", None) in (list, list)),
            next(iter(target_model.model_fields))
        )
        return target_model(**{list_field: parsed_data})


def _loads_with_repair(cleaned: str, original_text: str) -> Any:
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass
    try:
        return json.loads(repair_truncated_json(cleaned))
    except json.JSONDecodeError as e:
        raise ValueError(
            f"{_('Could not decode or repair JSON generated by LLM:')} {e}\n"
            f"{_('Original raw text:')}\n{original_text}"
        )


def tool_call_args(response, list_field: str) -> dict:
    """Extract and normalize LLM tool call arguments (coerce list field)."""
    args = response.tool_calls[0]["args"]
    if isinstance(args, str):
        try:
            args = json.loads(args)
        except Exception:
            args = {}
    if isinstance(args, dict):
        args[list_field] = safe_parse_json_list(args.get(list_field))
    return args
